### ISSUE TITLE
Documentation embedded diagrams

### ISSUE THREAD

**Issue by Jehan-David** [structurizr/structurizr#95] opened 2022-07-05 07:49 UTC
On the documentation, we've made a document around 15+ diagrams.

The firsts load correctly but it seems the lasts embedded diagrams don't work if you have too many in a single web page :

![image](https://user-images.githubusercontent.com/105345518/177276445-9e7af47e-3611-4a4c-b2e9-3c384e97a076.png)

I add we use a structurizr on-premise release.

Thank you for any support on that matter.

**Comment by simonbrowndotje** [comment] 2022-07-05 08:21
It's hard to say what the problem is without more information I'm afraid. Is this the built-in Markdown/AsciiDoc documentation, or are you embedding the diagrams via a HTML iframe? How many diagrams are included in the documentation? One section or many? etc

**Comment by simonbrowndotje** [comment] 2022-07-05 09:25
I've just created a quick workspace with 10 diagrams, and a documentation page showing them multiple times, which works as expected (see below).

Do the diagrams render via the diagram viewer, when not embedded?

```
workspace {

    model {
        softwareSystem = softwareSystem "Software System" {
            !docs docs
        }
    }

    views {
        systemContext softwareSystem "Diagram1" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram2" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram3" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram4" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram5" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram6" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram7" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram8" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram9" {
            include *
            autoLayout
        }

        systemContext softwareSystem "Diagram10" {
            include *
            autoLayout
        }
    }

}
```

```
## Title

Some text...

![](embed:Diagram1)

![](embed:Diagram2)

![](embed:Diagram3)

![](embed:Diagram4)

![](embed:Diagram5)

![](embed:Diagram6)

![](embed:Diagram7)

![](embed:Diagram8)

![](embed:Diagram9)

![](embed:Diagram10)

![](embed:Diagram1)

![](embed:Diagram2)

![](embed:Diagram3)

![](embed:Diagram4)

![](embed:Diagram5)

![](embed:Diagram6)

![](embed:Diagram7)

![](embed:Diagram8)

![](embed:Diagram9)

![](embed:Diagram10)

![](embed:Diagram1)

![](embed:Diagram2)

![](embed:Diagram3)

![](embed:Diagram4)

![](embed:Diagram5)

![](embed:Diagram6)

![](embed:Diagram7)

![](embed:Diagram8)

![](embed:Diagram9)

![](embed:Diagram10)

![](embed:Diagram1)

![](embed:Diagram2)

![](embed:Diagram3)

![](embed:Diagram4)

![](embed:Diagram5)

![](embed:Diagram6)

![](embed:Diagram7)

![](embed:Diagram8)

![](embed:Diagram9)

![](embed:Diagram10)

![](embed:Diagram1)

![](embed:Diagram2)

![](embed:Diagram3)

![](embed:Diagram4)

![](embed:Diagram5)

![](embed:Diagram6)

![](embed:Diagram7)

![](embed:Diagram8)

![](embed:Diagram9)

![](embed:Diagram10)

```

**Comment by Jehan-David** [comment] 2022-07-05 15:46
We are on the 2757 build. 

For privacy reasons, I prefer to not send you the data. 

Maybe if that helps or if it you want more info from my browser. I've go these messages on the JS part :

![image](https://user-images.githubusercontent.com/105345518/177366706-a3c1fae7-6fc2-40af-8a03-519b4f63213e.png)

**Comment by simonbrowndotje** [comment] 2022-07-05 16:26
`ERR_INSUFFICIENT_RESOURCES` sounds like your web browser is running out of memory. You could try upgrading your browser, using another browser, or perhaps even another computer to confirm that this is the case.

**Comment by Jehan-David** [comment] 2022-07-06 07:43
I have got 32GB of RAM. We have already encountered the same issue on different PCs with different browsers. (Edge and Chrome)
![image](https://user-images.githubusercontent.com/105345518/177495504-0188221a-19d2-426a-9316-f162cd0d1e87.png)

Do you think the internal server we have can provoke this kind of error ? Maybe it has not enough memory. I don't investigate that possibility yet.

**Comment by simonbrowndotje** [comment] 2022-07-06 07:48
> Do you think the internal server we have can provoke this kind of error ?

Probably not ... `net::ERR_INSUFFICIENT_RESOURCES` looks like a client-side problem.

**Comment by Jehan-David** [comment] 2022-07-06 08:32
I made some tests on my side. I almost always can reproduce the behavior on Chrome. On the bright side it seems to work correctly on Firefox. It takes time but they are loaded.

Maybe, there is an issue with Chromium based browser.

**Comment by simonbrowndotje** [comment] 2022-07-06 08:43
If you export the workspace to a JSON file, how large is the resulting file?

**Comment by Jehan-David** [comment] 2022-07-06 08:46
It is little less than 2 MB

![image](https://user-images.githubusercontent.com/105345518/177509717-9e226e2a-f08a-40c2-8b32-29d4c404d438.png)

**Comment by Jehan-David** [comment] 2022-08-04 08:24
I'm coming back on this particular subject. We have multiple users encountering the exact same problem (we have good PC so I really doubt, it can be a reason). Plus, I confirm it's always on Chrome or Edge browsers. Firefox doesn't have the issue.

For now, we use this knowledge as a work around to display documentation but it is not very convenient.

Do you investigate further more this problem ?

**Comment by simonbrowndotje** [comment] 2022-08-04 10:37
We have tried to reproduce the issue, but without success I’m afraid. If you’re unable to email us the workspace (or even a sanitised version that still has the problem), something  you could try is using Structurizr Lite to render the workspace … this would at least remove your on-premises installation as variable.

**Comment by Jehan-David** [comment] 2022-08-05 07:48
I have sent you an example to help@structurizr.com

**Comment by simonbrowndotje** [comment] 2022-08-19 10:57
I just wanted to add a closing comment for anybody that finds this in the future ... it seems that Chrome has a limit on the number of pending HTTP requests that can be made, and having a large number of embedded diagrams is causing this limit to be breached. From the e-mailed `workspace.dsl` file, I can see that:

1. The single DSL file is defining a number of software systems in detail. Generally, the recommendation is that a workspace defines the detail for a single software system (https://structurizr.com/help/usage-recommendations) … so you’d have 1 workspace defining the details (containers, components, docs, ADRs) of software system A, another defining the details of software system "B", etc. The DSL workspace extension feature (https://github.com/structurizr/dsl/tree/master/docs/cookbook/workspace-extension) allows you to define a single “system landscape” workspace, with further workspaces (one per software system) to elaborate the details.

2. The documentation is being associated with the workspace, rather than individual software systems. The `!docs` statement can be used inside the `workspace` element (as was being done here), and also inside the `softwareSystem` element. I’d recommend splitting the documentation up into different directories, one per software system. You can then do something like this:

```
a = softwareSystem "A" {
    !docs docs/software-system-a
    …
}
b = softwareSystem "B" {
    !docs docs/software-system-b
    …
}
```

Splitting the documentation will mean that this problem won't happen, because the documentation will be rendered per software system, and you’ll never see all embedded diagrams on a single page.

**Closed by simonbrowndotje** 2022-08-19 10:57 UTC
